cmake_minimum_required(VERSION 3.20)

get_filename_component(REPO_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(ZIG_ROOT "${REPO_ROOT}/tools/zig")
set(ZIG_EXE "${ZIG_ROOT}/zig")

set(CMAKE_C_COMPILER   "${ZIG_EXE}" cc)
set(CMAKE_CXX_COMPILER "${ZIG_EXE}" c++)

# THIS IS THE ONLY LINE THAT ACTUALLY WORKS — FROM ZIG'S OWN CMAKE SUPPORT
set(CMAKE_C_COMPILE_OPTIONS_CREATE_C_RESPONSE_FILE "@<FILE>")
set(CMAKE_C_COMPILE_OPTIONS_CREATE_CXX_RESPONSE_FILE "@<FILE>")

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_C_COMPILER_TARGET x86_64-linux-gnu)
set(CMAKE_CXX_COMPILER_TARGET x86_64-linux-gnu)

set(CMAKE_C_FLAGS_RELEASE "-O3 -DNDEBUG")
set(CMAKE_CXX_FLAGS_RELEASE "-O3 -DNDEBUG")

if(NOT EXISTS "${ZIG_EXE}")
    message(FATAL_ERROR "Zig not found at ${ZIG_EXE}")
endif()

message(STATUS "Zig compiler → ${ZIG_EXE} cc")